In [2]:
import numpy as np

In [3]:
s1=np.arange(1,11,1)
s1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
s1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
s2=np.arange(1,21,1)
s2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
s2[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
import pandas as pd

In [8]:
data={'apples':3,'bananas':2,'oranges':1}
series=pd.Series(data)
series['pears']=4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [10]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 35, 40, 28, 32, 26, 29, 31, 27],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
},columns=['name','age','gender'])
df



name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eva   28      F
5    Frank   32      M
6    Grace   26      F
7   Hannah   29      F
8      Ian   31      M
9     Jack   27      M

In [11]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   28      F     Manager
5    Frank   32      M     Analyst
6    Grace   26      F  Programmer
7   Hannah   29      F     Manager
8      Ian   31      M     Analyst
9     Jack   27      M  Programmer


In [12]:
filtered_df=df[df['age']>=30]
print(filtered_df)

      name  age gender  occupation
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
5    Frank   32      M     Analyst
8      Ian   31      M     Analyst


In [15]:
# Save DataFrame to a CSV file
data = pd.read_csv('data.csv')
data
# Read the CSV file
df_new = pd.read_csv('data.csv')

# Display contents
print(df_new)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   28      F     Manager
5    Frank   32      M     Analyst
6    Grace   26      F  Programmer
7   Hannah   29      F     Manager
8      Ian   31      M     Analyst
9     Jack   27      M  Programmer
